version: "3.9"

services:
  frontend:
    build: .
    container_name: orcestra_frontend
    restart: always
    # Não exponha mais a porta 4173 para fora (o Nginx Proxy Manager vai acessar internamente pela porta 80)

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "81:81"      # Interface admin do NPM
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt